### ISSUE TITLE
AMBER error: No enum constant _GL000226.1

### ISSUE THREAD

**Issue by pdiakumis** [umccr/cnv-callers#4]
Getting this after AMBER enters the 'Calculating BAFs' phase:

```
13:15:05 - AMBER version: 1.5
13:15:05 - Loading tumor file ../../data/nogit/purple/amber/COLO829_tumor.mpileup
13:15:25 - Loading reference file ../../data/nogit/purple/amber/COLO829_normal.mpileup
13:15:45 - Calculating BAFs
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.hartwig.hmftools.common.chromosome.HumanChromosome._GL000226.1
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.hartwig.hmftools.common.chromosome.HumanChromosome.valueOf(HumanChromosome.java:12)
        at com.hartwig.hmftools.common.chromosome.HumanChromosome.fromString(HumanChromosome.java:70)
        at com.hartwig.hmftools.common.position.GenomePosition.compareTo(GenomePosition.java:24)
        at com.hartwig.hmftools.common.position.GenomePositionSelectorImpl.select(GenomePositionSelectorImpl.java:32)
        at com.hartwig.hmftools.amber.BAFFactory.create(BAFFactory.java:50)
        at com.hartwig.hmftools.amber.AmberApplication.<init>(AmberApplication.java:76)
        at com.hartwig.hmftools.amber.AmberApplication.main(AmberApplication.java:46)
```

**Comment by pdiakumis** [comment]
I think it just needs the standard chromosomes in the mpileup file. So the BED file containing the heterozygous loci (generated using bcftools + vcf2bed) needs to ignore non-standard chromosomes. For this case I can just remove the non-standard chromosome SNPs from the mpileups and proceed.

* Count of different mpileup chromosomes - the HCC2218 data only had the standard ones:

```
spartan ~/punim0010/projects/Diakumis_COLO829-sv-exploration/data/nogit/purple/amber $ 
cut -f1 COLO829_tumor.mpileup | sort | uniq | wc -l
80
```

* AMBER code at this [commit](https://github.com/hartwigmedical/hmftools/blob/4ea5f7c523fd96e9e3d1929061d3ea4a07bb4c67/hmf-common/src/main/java/com/hartwig/hmftools/common/chromosome/HumanChromosome.java#L12):

```
public enum HumanChromosome implements Chromosome {
    _1(true, false),
    _2(true, false),
   [...]
    _21(true, false),
    _22(true, false),
    _X(false, true),
    _Y(false, true),
    _MT(false, false);
```

**Comment by pdiakumis** [comment]
Sorted it out with: 

```
grep -v "GL000" COLO829_tumor.mpileup > COLO829_tumor.flt.mpileup
grep -v "GL000" COLO829_normal.mpileup > COLO829_normal.flt.mpileup
```
